name = "ultracare"
compatibility_date = "2026-01-27"

compatibility_flags = ["nodejs_compat"]

main = "src/main.tsx"

[env.stage]
name = "ultracare-stage"
compatibility_flags = ["nodejs_compat"]
main = "src/main.tsx"

[env.production]
name = "ultracare-prod"
compatibility_flags = ["nodejs_compat"]
main = "src/main.tsx"